### PR TITLE
add md5 check for downloaded JGI file

### PR DESCRIPTION
**Pull request by orangeSi**

### CODE REVIEW

**Comment by orangeSi** [comment]
Sometime curl exit with code 0 after finished download file, but the file in fact is not intact, maybe the network problem cause this. So validated the completeness of downloaded file by md5 value maybe needed, that is why this pull request is here.

**Review by glarue — APPROVED** [review]
Will make a few changes on the `md5` branch and then merge into `master`.

**Comment by glarue** [comment]
Commit d89dc1081e7f3cb98937b96b931920109c343aac integrates my implementation of the changes initialized in #9.

**Comment by glarue** [comment]
> Sometime curl exit with code 0 after finished download file, but the file in fact is not intact, maybe the network problem cause this. So validated the completeness of downloaded file by md5 value maybe needed, that is why this pull request is here.

I didn't say before, but this is a good feature I've been meaning to add for some time. Thanks for your initial work setting it up—I modified it slightly to match the style/approach of the script overall, but the general design was good.

**Pull request merged**
