### PR TITLE
Strptime does not handle most timezones, python-dateutil does.

### PR DESCRIPTION
**Pull request by calizarr**
time.strptime does not handle any timezone that isn't local to your machine or UTC/GMT. I added python-dateutil and used its parser (dateutil.parser) to handle the date case.

There are other fixes that don't involve adding in a new module, but that would depend on JGI not changing their timestamp generally or finding the timezone in the date string and removing it before parsing.

Also, apparently did some auto PEP8 fixes.

### CODE REVIEW

**Comment by glarue** [comment]
Can you give an example of how the original implementation could cause problems? As JGI is based in California, it's unlikely their usage will deviate from the standards set in their API sample XML, and I feel it's nicer for the end-user to stick to the standard library if possible.

**Comment by calizarr** [comment]
Here is the error I get running the original:
```
Raw Data:
Traceback (most recent call last):
  File "/home/clizarraga/Forked_Repos/jgi-query/jgi-query.py", line 741, in <module>
    url_dict = print_data(file_list, organism)
  File "/home/clizarraga/Forked_Repos/jgi-query/jgi-query.py", line 343, in print_data
    date = shorten_timestamp(i["timestamp"])
  File "/home/clizarraga/Forked_Repos/jgi-query/jgi-query.py", line 313, in shorten_timestamp
    time_info = time.strptime(time_string, "%a %b %d %H:%M:%S %Z %Y")
  File "/home/clizarraga/usr/python/bin/lib/python3.4/_strptime.py", line 494, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/home/clizarraga/usr/python/bin/lib/python3.4/_strptime.py", line 337, in _strptime
    (data_string, format))
ValueError: time data 'Fri Jan 21 12:46:39 PST 2011' does not match format '%a %b %d %H:%M:%S %Z %Y'
```

I traced it down to the %Z which is the time zone. If I check what timezones my local machine has from time I have aside from UTC and GMT:
```
>>> time.tzname
('CST', 'CDT')
```

PST does not exist for me and I get that error.

The bug report involving strptime and time zones:
https://bugs.python.org/issue22377

If JGI were to keep their time format constant, then one could remove the timezone using only Python standard libraries:
```
indices = [0, 1, 2, 3, 5]
time_string = ' '.join([time_string.split(' ')[i] for i in indices])
time_info = time.strptime(time_string, "%a %b %d %H:%M:%S %Y")
```

**Comment by glarue** [comment]
Thank you, I didn't fully appreciate what the issue was before. It's a bit silly for me to have used the time library here at all, actually, since we're only getting the year anyway. Originally, I was pulling in more than just the year, which is (I think) why I bothered with it at all. At any rate, we can keep the standard library implementation and just regex out the offending timezone string:

```python
def shorten_timestamp(time_string):
    """
    Parses the timestamp string from an XML document
    of the form "Thu Feb 27 16:38:54 PST 2014"
    and returns a string of the form "2014".

    """
    # Remove platform-dependent timezone substring
    # of the general form "xxT"
    tz_pattern = re.compile("\s[A-Z]{2}T\s")
    time_string = tz_pattern.sub(" ", time_string)

    # Get the desired time info
    time_info = time.strptime(time_string, "%a %b %d %H:%M:%S %Y")
    year = str(time_info.tm_year)
    return year
```

Please let me know if this doesn't work on your end.

**Comment by calizarr** [comment]
The only concern I would have about that is if the timezone is in UTC which I don't believe the regex is catching. Otherwise, it is working for me now.

**Comment by glarue** [comment]
[D'oh!](https://youtu.be/H22t-tiWiLw) Fixed.

**Pull request closed without merging**
