### PR TITLE
Files decompress automatically (even when told not to)

### PR DESCRIPTION
**Pull request by calizarr**
When asked to decompress files in jgi-query.py even if answer is "n" the script continues and decompresses files. For a lot of files (especially large ones), this makes it seem like it froze and wasn't working correctly.

The original line with two strings inside the input() seemed to be the problem. Once I changed it to one string and tested it there were no problems.

### CODE REVIEW

**Comment by glarue** [comment]
Strange, this does not happen for me. What type of system are you running on, and with what version of Python?

**Comment by glarue** [comment]
I've refactored the script in `master` to comply with PEP8, and (I presume) also fix this issue. I'm still curious about what caused the difference in behavior, though.

**Comment by calizarr** [comment]
I'm using Python 3.4 and CentOS 6 & CentOS 7. The same thing happened on both.

**Comment by glarue** [comment]
Well, nothing obvious comes to mind, though all of my testing is done on Mint/Gentoo. I'm not sure what the proper etiquette is on GitHub for this type of thing, but I hope it's not a problem that I've changed it from my end (as your solution contained a non-PEP8 line). Also, seems like your pull request still includes the alternate `dateutil` approach, which for reasons specified earlier I am disinclined to merge in.

**Comment by calizarr** [comment]
I'm not entirely certain either. Yeah, PEP8 line lengths tend to be short.

The commit is included in it, but your fix came in after it so the script itself (jgi-query.py) contains the proper fix without the dateutil and with the regex fix.

**Comment by glarue** [comment]
I appreciate your work on troubleshooting this stuff. I promise the next fix I will actually merge in!

**Comment by calizarr** [comment]
Thanks. It's good.

I was so frustrated by JGI's system that I almost gave up when I
encountered the original error, so I'm glad I can be of help in making it
work if it even helps only one other person to deal with JGI's system +
infrastructure sans GUI + downloading files.

It is ridiculously frustrating and with your project way less so. So thank
you.

**Comment by glarue** [comment]
I hear you. I wrote the thing initially because I was so tired of first `wget`ing and later having to download data onto my personal computer before uploading to our server. It's gratifying to know someone else has found it useful.

**Pull request closed without merging**
